### ISSUE TITLE
need help train it 

### ISSUE THREAD

**Issue by bsun0802** [oss-roettger/XL-Textual-Inversion#1]
Hi thanks for contributing this and I've starred your repo! However, it seems it train fails in the latest diffuser repo version. 

I followed the notebook exactly, but there are some errors (one on the time_ids = base._get_add_time_ids(...) function call), I tried to fixed them and it is runnable, but I don't fully understand it. 

And it trains to NaN
![image](https://github.com/oss-roettger/XL-Textual-Inversion/assets/39657051/6692497f-962e-44d5-a08b-735bc51aa7cf)

I'm using
torch                        2.1.0
diffusers                 0.24.0.dev0

Could you help try running it in latest diffusers and push changes? Or add a working "requirements.txt" to the repo? Thanks!

**Comment by oss-roettger** [comment]
Dear Bo Sun,
ML optimization in general can sometimes lead to parameters vanishing to zero or infinity - both lead to "nan".
Your screenshot looks like the optimization process started well and went to "nan" eventually in the second half.
Please try the following:
* change the torch.manual_seed(46) to a different number e.g. 42 # different Randoms lead to different optimizations
* set imgs_flip=True, to use flipped input images additionally # the more images the less the "nan" appearance
* to get good results please use input images with the same image ratio e.g. 1:1 and define the imgs_wh accordingly - default is imgs_wh=(768,768) # width/height; Try lower resolutions e.g. (512,512) first to get results faster
* You can also try to reduce the learning rates e.g. learning_rates=[(35,6e-4),(60,5e-4),(100,4e-4),(160,3e-4)]

Hope this helps! Please get in touch again, if the above does not work.

**Comment by bsun0802** [comment]
Thanks, I will find a time to try it out.  One ting I want to bring is just "_get_add_time_ids()" this function now requires me to add a dimension arg, otherwise the notebook will error. I just want to make sure it is not the added args is causing problem.

**Comment by oss-roettger** [comment]
Thanks, Bo Sun. I've already updated the "time_ids" issue in the notebook. The diffusers API had changed.
