### ISSUE TITLE
About the function ‘force_training_grad’

### ISSUE THREAD

**Issue by ucasligang** [oss-roettger/XL-Textual-Inversion#3]
Great job, but I have a question about the code in the ‘XL_Apply_Inversion.ipynb’ file. In the code snippet:
```
with torch.enable_grad():
    # Switch Models into training mode
    force_training_grad(XLunet,True,True)
    force_training_grad(XLt1,True,True)
    force_training_grad(XLt2,True,True)
```

Shouldn't the first argument in these calls be set to False? Because we only need to update the text embedding, not the entire network.

**Comment by oss-roettger** [comment]
Dear Gang Li,
thanks, you are right and even more: **the force_training_grad() calls have no effect at all** (at least with diffuser V 0.24.0)! During development I had some trouble getting the gradients, so I tried everything to force it.
You might expect that force_training_grad(False,True) would save you some VRAM, but it does not effect memory consumption either. Therefore I will leave the source code unchanged ('never change a running system').
Kind regards
Hans
