### ISSUE TITLE
GPU mem increase to almost 80G on a A100 but just 20G on a V100

### ISSUE THREAD

**Issue by Deaddawn** [oss-roettger/XL-Textual-Inversion#4]
Hi, there. I met this strange problem as mentioned, does that make sense to you?

**Comment by oss-roettger** [comment]
Hi, I have no access to an A100 myself, but I guess the bfloat16 datatype is suboptimal for an A100 - have you already tried to to load the base model in a different torch_dtype? At least torch.float32 should use 40 GB 'only'.

    base = DiffusionPipeline.from_pretrained(
        ...
        torch_dtype=torch.float32,
        ...
    )

**Comment by Deaddawn** [comment]
> Hi, I have no access to an A100 myself, but I guess the bfloat16 datatype is suboptimal for an A100 - have you already tried to to load the base model in a different torch_dtype? At least torch.float32 should use 40 GB 'only'.
> 
> ```
> base = DiffusionPipeline.from_pretrained(
>     ...
>     torch_dtype=torch.float32,
>     ...
> )
> ```

I see, i will try your advice, thanks. BTW, is it must to use float32? is float16 available?

**Comment by oss-roettger** [comment]
I had some problems when using torch.float16 with gradients vanishing to 0 and resulting errors - therefore I used torch..bfloat16.
torch.float32 should give you the best results (if you have enough VRAM) , since the base model is float32.

**Comment by Deaddawn** [comment]
> I had some problems when using torch.float16 with gradients vanishing to 0 and resulting errors - therefore I used torch..bfloat16. torch.float32 should give you the best results (if you have enough VRAM) , since the base model is float32.

got it, thanks
