### ISSUE TITLE
training with fp16 get error

### ISSUE THREAD

**Issue by Deaddawn** [oss-roettger/XL-Textual-Inversion#6]
Hi, there. I am using fp16 to train a embedding, but get error when using apply script. Here is my setting:

xl_inversion.py:

base = DiffusionPipeline.from_pretrained(
    base_model_path, 
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=False,
    add_watermarker=False,
    # use DDPM DDPMScheduler instead of default EulerDiscreteScheduler 
    scheduler = DDPMScheduler(num_train_timesteps=1000,prediction_type="epsilon",beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False)
)
base.disable_xformers_memory_efficient_attention()

xl_apply.py:

base = DiffusionPipeline.from_pretrained(
    base_path, 
    torch_dtype=torch.float16, #torch.bfloat16
    variant="fp16", 
    use_safetensors=True,
    add_watermarker=False,
)
base.enable_xformers_memory_efficient_attention()
torch.set_grad_enabled(False)
_=base.to("cuda:1")

refiner = DiffusionPipeline.from_pretrained(
    refiner_path,
    text_encoder_2=base.text_encoder_2,  
    vae=base.vae,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
    add_watermarker=False,
)
refiner.enable_xformers_memory_efficient_attention()
_=refiner.to("cuda:1")

**get this error: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")**

the pic generated is all black like this:

![image](https://github.com/oss-roettger/XL-Textual-Inversion/assets/68223661/0bd51990-c912-4220-bf87-3a2192847195)

**Comment by Deaddawn** [comment]
seems fp16 will lead to lr to nan

**Comment by oss-roettger** [comment]
That is exactly what I told you 4 days ago and the reason why I have chosen bfloat16 for my implementation - nice  that you have changed the code to verified that on your own ;-)
see https://github.com/oss-roettger/XL-Textual-Inversion/issues/4#issuecomment-1880250074
