### ISSUE TITLE
 how to change batch size?

### ISSUE THREAD

**Issue by Deaddawn** [oss-roettger/XL-Textual-Inversion#7]
Hi ,there. Notice that you have a "batch_size" in xl_inversion.py but haven't been accessed, how do i use it?

**Comment by oss-roettger** [comment]
Hi Deaddawn, with the current implementation it is not possible to change the batch_size and for most of us this would make no sense because a bigger batch size would need far more VRAM. I was glad to get SDXL TI working within 24GB so I have not even tried to implement that.
